import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import Form from '../components/form'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Passport Checker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to passport checker!
        </Title>
          <Form />


        <Cards />
      </Main>
    </Container>
  )
}
